devops/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rdcheck/', include('rdcheck.urls')),
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name='index'),
    path('hosts', views.hosts, name='hosts'),
]

rdcheck/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'rdcheck'
urlpatterns = [
    path('', views.index, name='index'),
    path('linux/', views.linux_roundcheck, name='linux'),
    path('oracle/', views.oracle_roundcheck, name='oracle'),
]

ansible_app/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models


# Create your models here.


# 应用的名称，简称， 等级
class t_app(models.Model):
    def __str__(self):
        return str(self.app_name)

    app_name = models.CharField('应用名', max_length=32, primary_key=True)
    app_level = models.CharField('级别', max_length=2, blank=True, null=True)
    app_sname = models.CharField('英文简称', max_length=16, blank=True, null=True)

    class Meta:
        app_label = 'inventory'
        verbose_name = '应用表'
        verbose_name_plural = '应用表'


# 主机表
class t_hosts(models.Model):
    os_choice = (
        ('linux', 'linux'),
        ('aix', 'aix'),
        ('windows', 'windows'),
    )
    db_choice = (
        ('oracle', 'oracle'),
        ('informix', 'informix'),
        ('db2', 'db2'),
        ('mysql', 'mysql'),
        (None, '无'),
    )
    device_choice = (
        ('V', '虚拟机'),
        ('P', '物理机'),
    )
    schema_choice = (
        ('db', 'db'),
        ('dg', 'dg'),
        ('rac', 'rac'),
        ('single', 'single'),
        (None, '无'),
    )
    rdcheck_choice = (
        (True, '是'),
        (False, '否'),
    )
    location = models.CharField('loc', max_length=10, blank=True, null=True)
    ip = models.CharField('ip', max_length=20, blank=True, null=False, primary_key=True)
    is_rdcheck = models.BooleanField('是否巡检', choices=rdcheck_choice, blank=False, default=True)
    os_type = models.CharField('OS', choices=os_choice, max_length=16, blank=True, null=True)
    os_version = models.CharField('版本', max_length=32, blank=True, null=True)
    device = models.CharField('设备类型', choices=device_choice, max_length=16, blank=True, null=True)
    db_type = models.CharField('数据库', choices=db_choice, max_length=16, blank=True, null=True)
    db_schema = models.CharField('数据库模式', choices=schema_choice, max_length=16, blank=True, null=True)
    hostname = models.CharField('主机名', max_length=32, blank=True, null=True)
    app = models.ForeignKey(t_app, on_delete=models.CASCADE)
    ts = models.DateTimeField('时间', auto_now=True)

    class Meta:
        app_label = 'inventory'
        verbose_name = '主机表'
        verbose_name_plural = '主机表'

    def __str__(self):
        return str('_'.join([self.ip, self.app.app_name]))

rdcheck/models.py
from django.db import models
from inventory.models import t_hosts


# Create your models here.
class t_linux_result(models.Model):
    ip = models.ForeignKey(t_hosts, on_delete=models.CASCADE)
    ts = models.DateTimeField('ts', auto_now=True)
    hostname = models.CharField('hostname', max_length=32, null=True)
    metric = models.JSONField('metric', null=True)

    def __str__(self):
        return str(self.ip)

    class Meta:
        verbose_name = 'linux巡检结果'
        verbose_name_plural = 'linux巡检结果'

report/models.py
from django.db import models

# Create your models here.

devops/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.

def index(request):
    #return HttpResponse("Hello,world.You are at the all index")
    return render(request, 'index.html')

inventory/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
from datetime import datetime, date
import pdb


def index(request):
    return HttpResponse("Hello,world.You are at the inventory index")


def hosts(request):
    pass

rdcheck/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
from datetime import datetime, date, timedelta
import pdb
from .models import t_linux_result
from inventory.models import t_hosts


# Create your views here.

class JsonCustomEncoder(json.JSONEncoder):
    """
    自定义一个支持序列化时间格式的类
    """

    def default(self, o):
        if isinstance(o, datetime):
            return o.strftime("%Y-%m-%d %H:%M:%S")
        elif isinstance(o, date):
            return o.strftime("%Y-%m-%d")
        else:
            return json.JSONEncoder.default(self, o)


def index(request):
    return HttpResponse("Hello,world.You are at the roundcheck index")


def linux_roundcheck(request):
    if request.method == 'GET':
        today = datetime.now()
        p1 = timedelta(days=1)
        hosts = t_linux_result.objects.filter(ts__range=[today.date(), (today+p1).date()])
    return render(request, 'rdcheck/os_linux.html', hosts)

def oracle_roundcheck(request):
    pass

report/views.py
from django.shortcuts import render

# Create your views here.

rdcheck/templates/rdcheck/os_linux.html
{% extends "base.html" %}
{% block basehead %}
    {{ block.super }}
    {% load static %}
    <!--datatables-->
    <meta http-equiv="refresh" content="720">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/buttons.dataTables.min.css' %}" />
    <script src="{% static 'report/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'report/datatables/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'report/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'report/datatables/jszip.min.js' %}"></script>
    <script src="{% static 'report/datatables/pdfmake.min.js' %}"></script>
    <script src="{% static 'report/datatables/vfs_fonts.js' %}"></script>
    <script src="{% static 'report/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'report/datatables/buttons.print.min.js' %}"></script>
{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block maincontent %}
          <table id="rdcheck_table" class="table table-striped table-bordered table-hover table-condensed">
              <caption><p class="text-primary" style="font-size: small">Linux巡检: 生产环境linux总计 {{ linux_host_total }} 台,已巡检 {{ check_num }}台，登记为<a href="#" style="color: green">忽略</a> {{ ignorehost_num }} 台, <a href="#" style="color: red">未巡检到</a>有{{ unroundcheck_num}}台; <a href="#" style="color: green">注: 为了快速获取指标的告警情况，推荐点击相应列的列头进行排序</a></p></caption>
            <thead>
            <tr>
              <th>采集时间</th>
              <th>ip</th>
              <th>主机名</th>
              <th>CPU</th>
              <th>内存</th>
              <th>swap</th>
              <th>m数据_max</th>
              <th>nfs_max</th>
              <th>inode</th>
              <th>zabbix</th>
              <th>NTP配置</th>
              <th>时差</th>
              <th>平台</th>
              <th>系统</th>
              <th>应用</th>
            </tr>
            </thead>
            <tbody>
                {% for host in hosts %}
                <tr>
                  <td>{{ host.ts|time }}</td>
                  <td>{{ host.ip }}</td>
                  <td>{{ host.hostname }}</td>
                {% if host.metric.cpu_used >= 90 %}
                  <td bgcolor="f7acbc">{{ host.metric.cpu_used }}%</td>
                  {% else %} <td>{{ host.metric.cpu_used }}%</td> {% endif %}
                {% if host.metric.mem_used >= 90 %}
                  <td bgcolor="f7acbc">{{ host.metric.mem_used }}%</td>
                  {% else %} <td>{{ host.metric.mem_used }}%</td> {% endif %}
                  <td>{{ host.metric.swap_used }}%</td>
                {% if host.metric.fs_root_used >= 80 %}
                  <td bgcolor="f7acbc">{{ host.metric.fs_root_used }}% 余{{ host.metric.fs_root_free|filesizeformat }}</td>
                  {% else %} <td>{{ host.metric.fs_root_used }}%</td> {% endif %}
                {% if host.metric.fs_data_used >= 80 %}
                  <td bgcolor="f7acbc">{{ host.metric.fs_data_used }}% 余{{ host.metric.fs_data_free|filesizeformat }}</td>
                  {% elif host.metric.fs_data_used == -1 %} <td>0</td>
                  {% else %} <td>{{ host.metric.fs_data_used }}%</td> {% endif %}
                {% if host.metric.inode_used >= 90 %}
                  <td bgcolor="f7acbc">{{ host.metric.inode_used }}%</td>
                {% else %} <td>{{ host.metric.inode_used }}%</td> {% endif %}
                {% if host.metric.fs_write == 'N' %}
                  <td bgcolor="f7acbc">{{ host.metric.fs_write }}
                      ReadOnlyList: {%  for ro in host.metric.readonly_fs %}<p style="color: green">{{ ro }}</p>{% endfor %}
                  </td>
                {% else %} <td>{{ host.metric.fs_write }}</td> {% endif %}
                <td>{{ host.metric.atom_agent }}</td>
                <td>{{ host.metric.zabbix_agent }}</td>
                <td>{{ host.metric.ntp_config }}</td>
                {% if host.metric.ntp_offset <= -100 or host.metric.ntp_offset >= 100 %}
                  <td bgcolor="f7acbc">{{ host.metric.ntp_offset }}</td>
                {% else %} <td>{{ host.metric.ntp_offset }}</td> {% endif %}
                  <td>{{ host.platform }}</td>
                  <td>{{ host.os_ver }}</td>
                  <td>{{ host.product }}</td>
                  <td>{{ host.ops_mgr }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
{% endblock %}
{% block tail_script %}

<script>
$(function () {
        $('#rdcheck_table').DataTable({
                "autoWidth":false,
                "iDisplayLength":-1,
                "sScrollX":"100%",
                "sScrollXInner":"100%",
                "paging":true,
                "scrollY":"70vh",
                "scroller":true,
                "bPaginate":false,"deferRender":true,
                "bLengthChange":false,
                "sZeroRecords": "没有检索到数据",
                "dom":"Bfrtip",
                "order": [[ 6, "desc"]],
                 "buttons": [ 'copyHtml5','excelHtml5','csvHtml5','pdfHtml5']
        });
      });
</script>

	<style>
		body,
		html {
			margin: 0;
			font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		}
		table.dataTable {
			width: 100%;
			margin: 0 auto;
			clear: both;
			border-collapse: separate;
			border-spacing: 0;
		}

		table.dataTable thead th,
		table.dataTable tfoot th {
			font-weight: bold;
		}

		table.dataTable thead th,
		table.dataTable thead td {
			padding: 10px 18px;
			border-bottom: 1px solid #111;
		}

		table.dataTable thead th:active,
		table.dataTable thead td:active {
			outline: none;
		}

		table.dataTable tfoot th,
		table.dataTable tfoot td {
			padding: 10px 18px 6px 18px;
			border-top: 1px solid #111;
		}

		table.dataTable tbody th,
		table.dataTable tbody td {
			padding: 8px 10px;
		}

		#table_wrapper {
			margin: 20px 40px;
		}

		table tr th,
		table tr td {
			text-align: left;
			white-space: nowrap;
		}

		#table_wrapper .dataTables_length,
		#table_wrapper .dataTables_filter {
			margin-bottom: 20px;
			font-size: 10px;
			text-transform: uppercase;
			float: right;
   		margin-left: 20px;
		}

		#table_wrapper .dataTables_length label,
		#table_wrapper .dataTables_filter label,
		#table_wrapper .dataTables_paginate a,
		#table_wrapper .dataTables_info {
			color: #039 !important;
		}

		#table_wrapper .dataTables_filter input {
			margin: 0 3px;
		}

		#table_wrapper .dataTables_paginate a,
		#table_wrapper .dataTables_info {
			font-size: 10px;
			text-transform: uppercase;
		}

		#table_wrapper .dataTables_paginate {
			float: right;
		}

		#table_wrapper .dataTables_paginate,
		#table_wrapper .dataTables_info {
			display: inline-block;
			margin-top: 10px;
		}

		#table_wrapper .dataTables_paginate a {
			padding: 3px 6px;
			margin: 0 5px;
			cursor: pointer;
		}

		#table_wrapper .dataTables_paginate a.current {
			color: #fff !important;
			background: #039;
		}

		#table_wrapper table {
			font-size: 12px;
			background: #fff;
			border-collapse: collapse;
			text-align: left;
			width: 100%;
		}

		#table_wrapper table caption {
			font-size: 20px;
			color: #039;
			text-align: left;
			margin-bottom: 10px;
		}

		#table_wrapper table th {
			font-size: 14px;
			font-weight: normal;
			color: #039;
			padding: 10px 8px;
			border-bottom: 2px solid #6678b1;
			position: relative;
		}

		#table_wrapper .dataTables_scrollHead th.sorting,
		#table_wrapper .dataTables_scrollHead th.sorting_asc,
		#table_wrapper .dataTables_scrollHead th.sorting_desc {
			position: relative;
			cursor: pointer;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:before,
		#table_wrapper .dataTables_scrollHead th.sorting_asc:before,
		#table_wrapper .dataTables_scrollHead th.sorting:after,
		#table_wrapper .dataTables_scrollHead th.sorting_desc:after {
			border: 4px solid transparent;
			position: absolute;
			display: block;
			content: "";
			height: 0;
			right: 8px;
			top: 50%;
			width: 0;
			opacity: 0.4;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:before,
		#table_wrapper .dataTables_scrollHead th.sorting_asc:before {
			border-bottom-color: #669;
			margin-top: -9px;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:after,
		#table_wrapper .dataTables_scrollHead th.sorting_desc:after {
			border-top-color: #669;
			margin-top: 1px;
		}

		#table_wrapper table td {
			border-bottom: 1px solid #ccc;
			color: #669;
			padding: 6px 8px;
		}

		#table_wrapper table tbody tr:hover td {
			color: #009;
		}

		.dt-buttons {
			display: inline-block;
		}

		.dt-button {
			color: #FFFFFF;
			background: #039;
			margin-right: 10px;
			padding: 6px 12px;
			cursor: pointer;
			-webkit-transition: all 60ms ease-in-out;
			transition: all 60ms ease-in-out;
			text-align: center;
			white-space: nowrap;
			text-decoration: none !important;
			text-transform: none;
			text-transform: capitalize;
			border: 0 none;
			border-radius: 2px;
			font-size: 11px;
			line-height: 1.3;
			text-transform: uppercase;
		}

		.dt-button-info {
			padding: 50px;
			color: #039;
			text-align: center;
			position: fixed;
			top: 0;
			left: 0;
			right: 0;
			bottom: 0;
			background: rgba(255, 255, 255, 0.7)
		}

		.dt-button-info h2 {
			display: none;
		}
        </style>
{% endblock %}

rdcheck/templates/rdcheck/tab_report.html
{% extends "base.html" %}
{% block basehead %}
    {{ block.super }}
    {% load staticfiles %}
    <!--datatables-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/buttons.dataTables.min.css' %}" />
    <script src="{% static 'report/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'report/datatables/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'report/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'report/datatables/jszip.min.js' %}"></script>
    <script src="{% static 'report/datatables/pdfmake.min.js' %}"></script>
    <script src="{% static 'report/datatables/vfs_fonts.js' %}"></script>
    <script src="{% static 'report/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'report/datatables/buttons.print.min.js' %}"></script>
{% endblock %}
{% block title %}报表展示{% endblock %}

{% block maincontent %}
            <p></p>
            <table id="cmdbtab" class="table table-striped table-bordered table-hover table-condensed">
                <caption><p class="text-primary" style="font-size: larger">>> &nbsp;{{ tab_url }}</p></caption>
            </table>
{% endblock %}
{% block tail_script %}
    	<script>
		$(document).ready(function() {
            $.post("{{ tab_url }}", function(data, status){
                $("#cmdbtab").DataTable({
                "autoWidth":false,
                "columns":data.columns,
                "data":data.data,
                "iDisplayLength":-1,
                "sScrollX":"100%",
                "sScrollXInner":"100%",
                "paging":true,
                 "scrollY":"70vh","scroller":true,
                "bPaginate":false,"deferRender":true,
                "bLengthChange":false,
                "sZeroRecords": "没有检索到数据",
                "dom":"Bfrtip",
                 "buttons": [ 'copyHtml5','excelHtml5','csvHtml5','pdfHtml5']});
             });
		});
	</script>
	<style>
		body,
		html {
			margin: 0;
			font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		}
		table.dataTable {
			width: 100%;
			margin: 0 auto;
			clear: both;
			border-collapse: separate;
			border-spacing: 0;
		}

		table.dataTable thead th,
		table.dataTable tfoot th {
			font-weight: bold;
		}

		table.dataTable thead th,
		table.dataTable thead td {
			padding: 10px 18px;
			border-bottom: 1px solid #111;
		}

		table.dataTable thead th:active,
		table.dataTable thead td:active {
			outline: none;
		}

		table.dataTable tfoot th,
		table.dataTable tfoot td {
			padding: 10px 18px 6px 18px;
			border-top: 1px solid #111;
		}

		table.dataTable tbody th,
		table.dataTable tbody td {
			padding: 8px 10px;
		}

		#table_wrapper {
			margin: 20px 40px;
		}

		table tr th,
		table tr td {
			text-align: left;
			white-space: nowrap;
		}

		#table_wrapper .dataTables_length,
		#table_wrapper .dataTables_filter {
			margin-bottom: 20px;
			font-size: 10px;
			text-transform: uppercase;
			float: right;
   		margin-left: 20px;
		}

		#table_wrapper .dataTables_length label,
		#table_wrapper .dataTables_filter label,
		#table_wrapper .dataTables_paginate a,
		#table_wrapper .dataTables_info {
			color: #039 !important;
		}

		#table_wrapper .dataTables_filter input {
			margin: 0 3px;
		}

		#table_wrapper .dataTables_paginate a,
		#table_wrapper .dataTables_info {
			font-size: 10px;
			text-transform: uppercase;
		}

		#table_wrapper .dataTables_paginate {
			float: right;
		}

		#table_wrapper .dataTables_paginate,
		#table_wrapper .dataTables_info {
			display: inline-block;
			margin-top: 10px;
		}

		#table_wrapper .dataTables_paginate a {
			padding: 3px 6px;
			margin: 0 5px;
			cursor: pointer;
		}

		#table_wrapper .dataTables_paginate a.current {
			color: #fff !important;
			background: #039;
		}

		#table_wrapper table {
			font-size: 12px;
			background: #fff;
			border-collapse: collapse;
			text-align: left;
			width: 100%;
		}

		#table_wrapper table caption {
			font-size: 20px;
			color: #039;
			text-align: left;
			margin-bottom: 10px;
		}

		#table_wrapper table th {
			font-size: 14px;
			font-weight: normal;
			color: #039;
			padding: 10px 8px;
			border-bottom: 2px solid #6678b1;
			position: relative;
		}

		#table_wrapper .dataTables_scrollHead th.sorting,
		#table_wrapper .dataTables_scrollHead th.sorting_asc,
		#table_wrapper .dataTables_scrollHead th.sorting_desc {
			position: relative;
			cursor: pointer;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:before,
		#table_wrapper .dataTables_scrollHead th.sorting_asc:before,
		#table_wrapper .dataTables_scrollHead th.sorting:after,
		#table_wrapper .dataTables_scrollHead th.sorting_desc:after {
			border: 4px solid transparent;
			position: absolute;
			display: block;
			content: "";
			height: 0;
			right: 8px;
			top: 50%;
			width: 0;
			opacity: 0.4;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:before,
		#table_wrapper .dataTables_scrollHead th.sorting_asc:before {
			border-bottom-color: #669;
			margin-top: -9px;
		}

		#table_wrapper .dataTables_scrollHead th.sorting:after,
		#table_wrapper .dataTables_scrollHead th.sorting_desc:after {
			border-top-color: #669;
			margin-top: 1px;
		}

		#table_wrapper table td {
			border-bottom: 1px solid #ccc;
			color: #669;
			padding: 6px 8px;
		}

		#table_wrapper table tbody tr:hover td {
			color: #009;
		}

		.dt-buttons {
			display: inline-block;
		}

		.dt-button {
			color: #FFFFFF;
			background: #039;
			margin-right: 10px;
			padding: 6px 12px;
			cursor: pointer;
			-webkit-transition: all 60ms ease-in-out;
			transition: all 60ms ease-in-out;
			text-align: center;
			white-space: nowrap;
			text-decoration: none !important;
			text-transform: none;
			text-transform: capitalize;
			border: 0 none;
			border-radius: 2px;
			font-size: 11px;
			line-height: 1.3;
			text-transform: uppercase;
		}

		.dt-button-info {
			padding: 50px;
			color: #039;
			text-align: center;
			position: fixed;
			top: 0;
			left: 0;
			right: 0;
			bottom: 0;
			background: rgba(255, 255, 255, 0.7)
		}

		.dt-button-info h2 {
			display: none;
		}
        </style>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    {% load static %}
    {% block basehead %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/pace/dataurl.css' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'js/bootstrap/html5shiv.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/respond.min.js' %}"></script>
    <![endif]-->
    <!--页面加载进度条-->
    <script src="{% static 'js/pace/pace.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrolltopcontrol/scrolltopcontrol.js' %}"></script>
    <script src="{% static 'js/jquery.extend.js' %}"></script>
    <script src="{% static 'js/default.js' %}"></script>
    {% endblock %}
    <title>{% block title %}运维开发{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle show pull-left" data-target="sidebar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">成都银行</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="http://10.128.128.156/duty" target="_blank">值班表</a></li>
                    <li><a href="http://10.0.8.85:8080/icms-auto" target="_blank">自动化运维平台</a></li>
                    <li><a href="http://10.128.128.219/zabbix" target="_blank">zabbix监控</a></li>
                    <li><a href="http://10.0.8.93:9999/login.html" target="_blank">集中告警平台</a></li>
                    <li><a href="http://10.0.8.42:8001/svn.html" target="_blank">部门SVN</a></li>
                    <li><a href="http://10.128.1.113/srcu/loginFromMDM.jsp" target="_blank">ITSM</a></li>
                    <li><a href="/cloud/" target="_blank">云平台信息</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                           <i class="fa fa-fw"></i>更多<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="http://10.0.8.20:8080/" target="_blank"><i class="fa fa-sign-out fa-fw"></i>&nbsp;TFS日报</a></li>
                            </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="/xadmin" role="button"><i class="fa fa-user fa-fw"></i>&nbsp;Login&nbsp;</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid all">
    {% block sidebar %}
        <div class="sidebar">
            <ul class="nav">
                <li><a href="javascript:void(0);">主页面</a></li>
                <li class="has-sub">
                    <a href="javascript:void(0);"><span>应用表</span><i class="fa fa-caret-right fa-fw pull-right"></i></a>
                    <ul class="sub-menu">
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="javascript:void(0);"><span>主机表</span><i class="fa fa-caret-right fa-fw pull-right"></i></a>
                    <ul class="sub-menu">
                    </ul>
                </li>

                <li class="has-sub">
                    <a href="javascript:void(0);"><span>巡检结果</span><i class="fa fa-caret-right fa-fw pull-right"></i></a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'rdcheck:linux' %}"><i class="fa fa-circle-o fa-fw"></i>Linux巡检</a></li>
                    </ul>
                    <ul class="sub-menu">
                        <li><a href="{% url 'rdcheck:oracle' %}"><i class="fa fa-circle-o fa-fw"></i>Oracle巡检</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    {% endblock %}
        <div id="maincontent" class="maincontent" >
            {% block maincontent %}{% endblock %}

        </div>
    </div>
    <a href="#top" id="goTop"><i class="fa fa-angle-up fa-3x"></i></a>
{% block tail_script %}{% endblock %}
</body>
</html>